name: R CMD CHECK

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libfontconfig1-dev libharfbuzz-dev  libfribidi-dev  libtiff-dev libjpeg-dev libwebp-dev pkg-config 
        shell: bash

      - name: Install dependencies
        run: |
          install.packages(c("devtools", "testthat"))
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run tests
        run: devtools::test()
        shell: Rscript {0}
